Repository raghsonlinedotcom/mini-project-tms, pull requests merged in 2022-12, with the labels that each got.

#1 Feature/create member - DB Scripts added
  src/main/sql/Database Scripts.sql
  src/main/webapp/META-INF/MANIFEST.MF
  src/main/webapp/Register.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/check.jsp
Labels: enhancement

#2 Documentation for human readability in SQL file
  src/main/sql/Database Scripts.sql
Labels: documentation, enhancement

#3 bugfix/TMS-24_ManagerIdNull Completed
  src/main/java/com/tutorials/tms/bo/Employee.java
  src/main/java/com/tutorials/tms/dao/EmployeeDAO.java
  src/main/java/com/tutorials/tms/dao/EmployeeDAOImpl.java
  src/main/java/com/tutorials/tms/db/DBConnection.java
  src/main/java/com/tutorials/tms/web/EmployeeCreateServlet.java
  src/main/webapp/check.jsp
  src/main/webapp/create.jsp
  src/main/webapp/index.jsp
Labels: bug

#5 TMS-24 | BugFix - ManagerId Null
  src/main/java/com/tutorials/tms/bo/Employee.java
  src/main/java/com/tutorials/tms/dao/EmployeeDAOImpl.java
  src/main/java/com/tutorials/tms/db/DBConnection.java
  src/main/java/com/tutorials/tms/web/EmployeeCreateServlet.java
  src/main/webapp/create.jsp
Labels: bug

#6 TMS23 - ConfigFile changes added
  src/main/java/com/tutorials/tms/dao/EmployeeDAO.java
  src/main/java/com/tutorials/tms/dao/EmployeeDAOImpl.java
  src/main/java/com/tutorials/tms/db/DBConnection.java
  src/main/java/com/tutorials/tms/util/PropertyUtil.java
  src/main/resources/config.properties
Labels: enhancement

#8 Customizable config add - config.properties(AppDevMode), dbconfig.properties added
  src/main/java/com/tutorials/tms/dao/EmployeeDAOImpl.java
  src/main/java/com/tutorials/tms/db/DBConnection.java
  src/main/java/com/tutorials/tms/util/AppUtil.java
  src/main/java/com/tutorials/tms/util/PropertyUtil.java
  src/main/mini-project-tms-gameplan-19Dec2022.md
  src/main/resources/config.properties
  src/main/resources/dbconfig.properties
  src/main/webapp/create.jsp
  src/main/webapp/style.css
Labels: documentation, enhancement

#12 Footer, Version updated
  src/main/webapp/footer.jsp
  src/main/webapp/version.jsp
Labels: documentation
